### ISSUE TITLE
Benchmark results for AMD Ryzen 5900x w/ NVIDIA RTX 4090

### ISSUE THREAD

**Issue by FireSilicon** [ShuiJu/CS2FPSBenchmark#2]
1 Ryzen 5 5900x

1-1 PBO on

2 RTX4090

2-1 PL at 70%, GPU gaming frequency at 2800Mhz

3 DDR4 3600CL16 XMP

4-1 1080P + All low settings  + No AA     : 471.8/186.0
4-2 1080P + All high settings + No AA     : 445.3/173.1
4-3 1080P + All high settings + 4x MSAA : 432.8/172.3
4-4 2160P + All high settings + No AA     : 347.5/127.8
4-5 2160P + All high settings + 4x MSAA : 325.0/137.9
4-6 4320P + All high settings + No AA     : 124.2/51.9

**Comment by ShuiJu** [comment]
8K omg
