### ISSUE TITLE
am5 7800x3d setup - 1080p /all low

### ISSUE THREAD

**Issue by wazerstar** [ShuiJu/CS2FPSBenchmark#3]
**1 CPU**

7800x3d
pbo undervolted each core ~ -18  > -45

![FmB42BA](https://github.com/ShuiJu/CS2FPSBenchmark/assets/4474519/45c75faa-587f-4aef-915e-7810e9e5c5ca)

**2 GPU**

3080 10gb founders edition, no oc

**3 RAM Speed and important timings, if XMP then just give freq.+XMP.**

32gb expo
6000mhz 
cl 28-36-36-30
![61sH0NH](https://github.com/ShuiJu/CS2FPSBenchmark/assets/4474519/9ffde072-d119-42da-9653-9e5feed19ae8)

**4 Avg FPS/P1 FPS**

avg 854.3 
P1=327.2

![OwtEzGf](https://github.com/ShuiJu/CS2FPSBenchmark/assets/4474519/c7ee4492-bccc-4a9d-b705-a4827329ac7e)

Test from 10 may 2024

**Comment by ShuiJu** [comment]
Did you use FSR?? Avg 854 FPS is way too wild for 3080...

**Comment by wazerstar** [comment]
> Did you use FSR?? Avg 854 FPS is way too wild for 3080...

It's not when you know how to setup your pc proper with 7800x3d and nvidia settings...

No I do fps optimization for people, you can see my settings here..


![20240514094610_1](https://github.com/ShuiJu/CS2FPSBenchmark/assets/4474519/ae0f64a3-fd27-46fe-887c-df026a3dc347)
![20240514094620_1](https://github.com/ShuiJu/CS2FPSBenchmark/assets/4474519/8781731a-f9b4-4f32-a257-aca540ae135f)


You can see all my screenshots, all the evidence is there, including screenshots of the actually fps avg and p1 lows in the console...

**Comment by wazerstar** [comment]
Also old clip from nov 2023 where cs was running really bad, I was still ahead of the game in DM look the fps.

https://streamable.com/2jxacl

**Comment by ShuiJu** [comment]
OK Don't worry it's just too shocking to see a 850 Avg FPS... I think people who are willing to share the results are not coming here to troll others. Very appreciate for you and your result!
![image](https://github.com/ShuiJu/CS2FPSBenchmark/assets/24865006/0205c2b3-2621-4d34-b042-e73baf1f37d4)

**Comment by wazerstar** [comment]
> OK Don't worry it's just too shocking to see a 850 Avg FPS... I think people who are willing to share the results are not coming here to troll others. Very appreciate for you and your result! ![image](https://private-user-images.githubusercontent.com/24865006/330335734-0205c2b3-2621-4d34-b042-e73baf1f37d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzQyMjAsIm5iZiI6MTcxNTY3MzkyMCwicGF0aCI6Ii8yNDg2NTAwNi8zMzAzMzU3MzQtMDIwNWMyYjMtMjYyMS00ZDM0LWIwNDItZTczYmFmMWYzN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTNkYWI4YjA3ODg3NGU1ZTNhODg5MjRhNzY5MzU5NGU0ZjlkNjc4NWVlZTE5ZGUwZjdlNGFhMDY3OWM4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKQ7l9GT8ugSpIlxepX1w3NmH2_OMGNlvG6zzABTX7A)

Thanks, tho however, the guys who created this made some big flaws, looking the camera up in the air during test which make my fps peek to around 1400-1600fps, if they had not done this the fps would be way more suited, so really its not a fault in my end, its whoever made this benchmark that made this f*ck up :)
