### ISSUE TITLE
i5-12400 + RX580 4GB 

### ISSUE THREAD

**Issue by ishakbas** [ShuiJu/CS2FPSBenchmark#5]
1. **CPU** Intel i5-12400 3994Mhz
> no OC, just stock turbo boost

2. **GPU** AMD RX580 4Gb powercolor 2100Mhz
> core undervolt 0.990V, memory OC 2100Mhz

3. **RAM** 3333Mhz
> OC from 3200 to 3333, lower timings (CR1 16-18-16-34)         

4. **Avg FPS/P1 FPS** 
> Avg=**324.4**, P1=**174.0** \ 1280:1024 \ [my settings](https://github.com/ShuiJu/CS2FPSBenchmark/assets/78724051/2836d25c-808b-44c6-99a6-c888181ed6f9) \ 

> Avg=**284.9**, P1=**177.8** \ 1920:1080 \ [my settings](https://github.com/ShuiJu/CS2FPSBenchmark/assets/78724051/2836d25c-808b-44c6-99a6-c888181ed6f9), but with perfomance FSR \ 

> Avg=**241.4**, P1=**124.4** \ 1280:1024 \ [recommended settings for weak gpu](https://github.com/ShuiJu/CS2FPSBenchmark?tab=readme-ov-file#my-recommended-setting-for-weak-gpu-is)  \ 

> Avg=**80.0**, P1=**42.2** \ 1920:1080 \ Maximum Preset \

**Date of benchmark**: 2024.05.20

**Comment by ShuiJu** [comment]
Thank you! Would you try my tuned settings? 
https://github.com/ShuiJu/CS2FPSBenchmark/tree/d87f274208f50be20a4e0ed6f03306beabc058bb/My%20graphics%20setting%20file
I think you need to change these lines to your values in your current cs2_video,txt to make it not instant reset:
	"Version"		"13"
	"VendorID"		"4318"
	"DeviceID"		"10464"
	"setting.cpu_level"		"3"
	"setting.gpu_mem_level"		"3"
	"setting.gpu_level"		"3"
	"setting.knowndevice"		"0"
Maybe it will brings you better image quality or better framerate... Hope so
If you need to use FSR, 
	"setting.r_csgo_fsr_upsample"		"0"
	"setting.mat_viewportscale"		"1.000000"
These two lines are needed for enabling FSR. 
r_csgo_fsr_upsample for FSR Performance it will become to 2, but I'm not sure if quality or balance got difference.
mat_viewportscale is render resolution scaling, performance is 0.5, which is 50%

**Comment by ishakbas** [comment]
with your config (nothing is not changed) FPS: Avg=173.9, P1=90.8
 with your config (enabled FSRP) FPS: Avg=212.7, P1=132.6

**Comment by ShuiJu** [comment]
Thank you so much and sorry that Value just killed my tweak this previous update....
