### ISSUE TITLE
5950X + 2080 Ti

### ISSUE THREAD

**Issue by devbork** [ShuiJu/CS2FPSBenchmark#6]
1 CPU

R9 5950X PBO enabled (default Ryzen master curve)

2 GPU

MSI 2080 Ti 11gb

3 RAM Speed and primary timings, if XMP then just give freq.+XMP.
3600mhz + XMP

4 Avg FPS/P1 FPS
1080p Low preset (no FSR) 410.8 avg, 155.7 P1
1080p Very high preset (no FSR) 250.7 avg, 123.9 P1

**Comment by ShuiJu** [comment]
gotcha
