### ISSUE TITLE
5950X + 4070 Super

### ISSUE THREAD

**Issue by devbork** [ShuiJu/CS2FPSBenchmark#7]
1 CPU

R9 5950X PBO enabled (default Ryzen master curve)

2 GPU

Asus 4070 Super EVO 12gb

3 RAM Speed and primary timings, if XMP then just give freq.+XMP.
3600mhz + XMP

4 Avg FPS/P1 FPS
1080p Low preset (no FSR) 462.2 avg, 160.2 P1
1080p Very high preset (no FSR) 311.4 avg, 133.0 P1

**Comment by ShuiJu** [comment]
gotcha
